# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    tags:
      - v0.*
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack TinyToolBox.Configuration
      run: |
        dotnet build -c Release src/TinyToolBox.Configuration/TinyToolBox.Configuration.csproj
        dotnet pack --no-build -c Release src/TinyToolBox.Configuration/TinyToolBox.Configuration.csproj -o .
    - name: Pack TinyToolBox.Configuration.AspNetCore
      run: | 
        dotnet build -c Release src/TinyToolBox.Configuration.AspNetCore/TinyToolBox.Configuration.AspNetCore.csproj
        dotnet pack --no-build -c Release src/TinyToolBox.Configuration.AspNetCore/TinyToolBox.Configuration.AspNetCore.csproj -o .
